export const SIGN_IN = 'SIGN_IN';
export const SIGN_OUT = 'SIGN_OUT';
export const SIGN_UP = 'SIGN_UP';
export const UPDATE_TOKEN = 'UPDATE_TOKEN';
export const AUTHENTICATE_TOKEN = 'AUTHENTICATE_TOKEN';

export const CURRENT_USER = 'CURRENT_USER';

export const FETCH_CATEGORIES = 'FETCH_CATEGORIES';
export const FETCH_CATEGORY = 'FETCH_CATEGORY';
export const UPDATE_CATEGORY = 'UPDATE_CATEGORY';
export const ADD_CATEGORY = 'ADD_CATEGORY';
export const DELETE_CATEGORY = 'DELETE_CATEGORY';

export const FETCH_ATTRIBUTES = 'FETCH_ATTRIBUTES';
export const FETCH_ATTRIBUTE = 'FETCH_ATTRIBUTE';
export const FETCH_ATTRIBUTES_BY_CATEGORY = 'FETCH_ATTRIBUTES_BY_CATEGORY';
export const UPDATE_ATTRIBUTE = 'UPDATE_ATTRIBUTE';
export const ADD_ATTRIBUTE = 'ADD_ATTRIBUTE';
export const ADD_ATTRIBUTES = 'ADD_ATTRIBUTES';
export const DELETE_ATTRIBUTE= 'DELETE_ATTRIBUTE';

export const FETCH_USER = 'FETCH_USER';
export const FORGOT_PASSWORD = 'FORGOT_PASSWORD';
export const CHANGE_PASSWORD = 'CHANGE_PASSWORD';